---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-deployment
  labels:
    app: go
spec:
  selector:
    matchLabels:
      app: go #标签
  replicas: 3 # 建立3个pod
  minReadySeconds: 5
  strategy:
    type: RollingUpdate # 更新策略为滚动更新
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: go
    spec:
      containers:
        - image: cuishuang/go-k8s-deploy-cuishuang:v1.3
          name: go
          imagePullPolicy: Always
          command: ["./main","-v","v1.3"]
          ports:
            - containerPort: 8080
              protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: go-service
  labels:
    app: go
spec:
  selector:
    app: go
  ports:
    - name: go-port
      protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 31080
  type: NodePort